name: Deploy to EC2 Staging Environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands 
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 3.6.7.193
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
              cd book-my-show
              git pull origin main
              pnpm install
              pnpm run build
              pm2 restart fe-server
              pm2 restart http-server
              pm2 restart ws-server
