name: Deploy to EC2 Staging Environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands 
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 3.6.7.193
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo apt update
            sudo apt install nodejs
            sudo apt install npm
            npm install -g pnpm
            node -v && npm -v && pnpm -v

